ALEAF_Master_LC_GEP:
  LC_GEP_settings:
    const_name_flag: "TRUE"
    export_model_lp_expansion_flag: "FALSE"
    export_model_lp_operation_flag: "FALSE"
    model_lp_file_name_value: ALEAF_LC_GEP_model_instance.lp
  planning_design:
    current_year_value:  2020
    final_year_value: 2021
    numstages_value: 1
    loadincreaserate_base_value: 0
    WACC_value: 0.058
    planning_reserve_margin: 0.1375
    enforce_min_reserve_margin_flag: "FALSE"
    num_days_per_OP_run_value: 1
    regulation_cost_scale_value: 0.2
    CTAX_in_MC_calculation_flag: "FALSE"
  simulation_settings:
    test_system_name: IL
    fuel_price_projection_flag: "FALSE"
    capex_projection_flag: "FALSE"
    generate_networkdata_flag: "TRUE"
    PDTF_threshold_value: 0.01
    power_flow_mode_flag: "None"
    bus_mapping_flag: "FALSE"
    network_reduction_flag: "FALSE"
    conduct_scenario_reduction_flag: "FALSE"
    big_M_value: 1.00e-5
    run_expansion_flag: "TRUE"
    run_operation_flag: "TRUE"
    num_scenario_value: 1
    per_unit_base_value: 1
    generation_outage_flag: "FALSE"
  scenario_settings:
    scenario_name: ALEAF_IL
    ATB_Setting: ATB_ID_1
    NDAYS: 7
    NDAYS_OP: 365
    HFREQ: 1
    FIVEMIN: 0
    FIVEMIN_OP: 0
    peak_demand: 30000
    VOLL: 9000
    SRSP: 1100
    NSRSP: 100
    MAXENS: 0
    MAXENSI: 9
    SCFC: 10000
    MAXEMS: 9999
    carbon_tax: 0
    RPS_percentage: 0
    wind_PTC: 0
    solar_PTC: 0
    nuclear_PTC: 0
    wind_ITC: 0
    solar_ITC: 0
    nuclear_ITC: 0
    CAPPMT: 0
  ALEAF_relative_file_paths:
    data_path: "data/LC_GEP"
    output_file_path: "output/LC_GEP"
    time_series_file_name: timeseries_hourly.csv
    timeseries_data_load_path: "timeseries_data_files/Load/timeseries_load_hourly.csv"
    timeseries_data_wind_path: "timeseries_data_files/WIND/timeseries_wind_hourly.csv"
    timeseries_data_pv_path: "timeseries_data_files/PV/timeseries_pv_hourly.csv"
    reserve_requirement_data_reg_path: "timeseries_data_files/Reserves/timeseries_reg_hourly.csv"
    reserve_requirement_data_spin_path: "timeseries_data_files/Reserves/timeseries_spin_hourly.csv"
    reserve_requirement_data_nspin_path: "timeseries_data_files/Reserves/timeseries_nspin_hourly.csv"
    timeseries_data_load_5mins_path: "timeseries_data_files/Load/timeseries_load_5mins.csv"
    timeseries_data_wind_5mins_path: "timeseries_data_files/WIND/timeseries_wind_5mins.csv"
    timeseries_data_pv_5mins_path: "timeseries_data_files/PV/timeseries_pv_5mins.csv"
    reserve_requirement_data_reg_5mins_path: "timeseries_data_files/Reserves/timeseries_reg_5mins.csv"
    reserve_requirement_data_spin_5mins_path: "timeseries_data_files/Reserves/timeseries_spin_5mins.csv"
    reserve_requirement_data_nspin_5mins_path: "timeseries_data_files/Reserves/timeseries_nspin_5mins.csv"
    timeseries_data_gen_outages_path: "timeseries_data_files/Outage/timeseries_gen_outage_hourly.csv"
  scenario_reduction_settings:
    time_resolution: Hourly
    fixing_extreme_days_flag: "TRUE"
    generate_input_data_flag: "TRUE"
    generate_duration_curve_flag: "FALSE"
    input_type_load_shape_flag: "TRUE"
    input_type_load_MWh_flag: "FALSE"
    input_type_wind_shape_flag: "TRUE"
    input_type_wind_MWh_flag: "FALSE"
    input_type_solar_shape_flag: "TRUE"
    input_type_solar_MWh_flag: "FALSE"
    input_type_net_load_MWh_flag: "FALSE"
ALEAF_Master:
  ALEAF_Master_setup:
    model_type: LC_GEP
    Master_data_file_name: ALEAF_Master_LC_GEP.xlsx
    solver_name: CPLEX
  CPLEX_settings:
    CPX_PARAM_PARAMDISPLAY: 1
    CPX_PARAM_EPGAP: 0.0001
    CPX_PARAM_MIPDISPLAY: 2
    CPX_PARAM_SCRIND: 0
    CPXPARAM_TimeLimit: 6000
    CPX_PARAM_EPRHS: 1.00e-6
    CPX_PARAM_THREADS: 4
    CPX_PARAM_NUMERICALEMPHASIS: 0
    CPX_PARAM_PREIND: 1
    CPX_PARAM_SCAIND: 1
    CPXPARAM_Simplex_Limits_Singularity: 10
    CPXPARAM_MIP_Tolerances_Integrality: 1.00e-5
    CPX_PARAM_AGGIND: -1
    CPXPARAM_Simplex_Tolerances_Markowitz: 0.9
    CPX_PARAM_LPMETHOD: 6
    CPX_PARAM_MIPEMPHASIS: 0
    CPX_PARAM_QTOLININD: 1
    CPXPARAM_MIP_Strategy_VariableSelect: 4
    CPXPARAM_MIP_Strategy_StartAlgorithm: 4
    CPXPARAM_MIP_Strategy_NodeSelect: 1
    CPXPARAM_WorkMem: 2048
    CPXPARAM_MIP_Strategy_File: 1
  HiGHS_settings:
    time_limit: 6000
    presolve: on
  Gurobi_settings:
    TimeLimit: 200
    MIPGap: 0.001
    OutputFlag: 1
    IntFeasTol: 1.00e-5
    FeasibilityTol: 1.00e-6
    DualReductions: 0
    Presolve: -1
    Aggregate: 1
    Threads: 4
    MIPFocus: 0
    NumericFocus: 0.0
    Cuts: 3.0
  GLPK_settings:
    tm_lim: 60000
    msg_lev: 4
  CBC_settings:
    seconds: 30    
ALEAF_portfolio:
  grid_settings:
    num_lines_value: 0
    num_zones_value: 1
    num_sub_area: 1
  buses:
    bus_i: 1
    bus_name: bus_ABC
    baseKV: 345
    bus type: ref
    MW load: 0
    MVAR load: 0
    area: 1
    sub area: 1
    zone: 1
    lat: 0
    lng: 0
    EAS_market_zone: 1
  branch:
    UID: A1
    f_bus: 1
    t_bus: 2
    br_r: 0.003
    br_x: 0.014
    br_b: 0.461
    rate_a: 175
    rate_b: 193
    rate_c: 200
    OutRate: 0.24
    Duration: 16
    Tr Ratio: 0
    OutRate: 0
    Length: 3
    model_flag: "TRUE"
  sub_area:
    sub_area_i: 1
    bus_name: sub_area_1
    baseKV: 345
    bus_type: ref
    area: 1
    sub_area: 11
    zone: 11
    EAS_market_zone: 1
  sub_area_mapping:
    bus_i: 1
    sub_area: 1




















