# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ABCE tests

on:
  workflow_dispatch: 
  push:
    branches: [ "main", "dev", "github_actions"]
  pull_request:
    branches: [ "main", "dev"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/biegelk/abce:latest

    steps:
    - uses: actions/checkout@v3


